# Generated by Django 5.1.7 on 2025-04-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_comment_edited_at_alter_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_pic',
            field=models.ImageField(blank=True, null=True, upload_to='comment_pics/'),
        ),
    ]
